// <auto-generated />

namespace PedaGo.UserMobileApp.iOS
{
    using Foundation;
    using ImageCircle.Forms.Plugin.iOS;
    using Prism;
    using Prism.Ioc;
    using UIKit;

    /// <summary>
    /// The UIApplicationDelegate for the application. This class is responsible for launching the 
    /// User Interface of the application, as well as listening (and optionally responding) to 
    /// application events from iOS.
    /// </summary>
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        // This method is invoked when the application has loaded and is ready to run. In this 
        // method you should instantiate the window, load the UI into it and then make the window
        // visible.
        // You have 17 seconds to return from this method, or iOS will terminate your application.
        /// <summary>
        /// When the app has finished launch
        /// </summary>
        /// <param name="app">Encapsulates the main processing loop for a MonoTouch application.</param>
        /// <param name="options">Dictionary that provides mapping from keys to values.</param>
        /// <returns>FinishedLaunching() method result</returns>
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            global::Xamarin.Forms.FormsMaterial.Init();
            ImageCircleRenderer.Init();

            this.LoadApplication(new App(new iOSInitializer()));

            return base.FinishedLaunching(app, options);
        }
    }

    public class iOSInitializer : IPlatformInitializer
    {
        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            // Register any platform specific implementations
        }
    }
}
