// <auto-generated />

namespace PedaGo.UserMobileApp.Droid
{
    using Android.App;
    using Android.Content.PM;
    using Android.OS;
    using ImageCircle.Forms.Plugin.Droid;
    using Plugin.CurrentActivity;
    using Plugin.Media;
    using Plugin.Permissions;
    using Prism;
    using Prism.Ioc;

    /// <summary>
    /// MainActivity Class
    /// </summary>
    [Activity(Label = "PedaGo.UserMobileApp", Icon = "@mipmap/ic_launcher", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override async void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar; ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            await CrossMedia.Current.Initialize();
            CrossCurrentActivity.Current.Init(this, bundle);
            //Xamarin.Essentials.Platform.Init(this, bundle);
            global::Xamarin.Forms.Forms.Init(this, bundle);
            global::Xamarin.Forms.FormsMaterial.Init(this, bundle);
            LoadApplication(new App());
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }

    public class AndroidInitializer : IPlatformInitializer
    {
        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            // Register any platform specific implementations
        }
    }
}

